--1) Find name of employee who earns more than 50K.
SELECT FIRSTNME, LASTNAME, SALARY FROM EMPLOYEE where salary > 50000;

--2) Show female employee who has education level of 16.
SELECT FIRSTNME, LASTNAME, EDLEVEL
FROM EMPLOYEE
WHERE SEX = 'F' and EDLEVEL = 16;

--3) Show employee who is younger than 40 years old.
SELECT FIRSTNME, LASTNAME, YEAR(CURRENT_DATE - BIRTHDATE) as AGE, BIRTHDATE
FROM EMPLOYEE
WHERE YEAR(CURRENT_DATE - BIRTHDATE) < 40;

--4) Find employee who has worked here for at least 10 years but not more than 20 years
SELECT FIRSTNME, LASTNAME, HIREDATE, CURRENT_DATE as CURRENT_DATE, year(CURRENT_DATE - HIREDATE) as WORKYEAR
FROM EMPLOYEE
WHERE year(CURRENT_DATE - HIREDATE) between 10 and 20;

--5) Show the project name and the length of the project (number of days)
SELECT PROJNAME, PRSTDATE, PRENDATE,
--        DAYS(PRSTDATE) as DAYS_PRSTDATE, DAYS(PRENDATE) as DAYS_PRENDATE,
--        DAY(PRSTDATE) as DAY_PRSTDATE, DAY(PRENDATE) as DAY_PRENDATE,
       DAYS(PRENDATE) - DAYS(PRSTDATE) as PROJECTLENGTH
FROM PROJECT
WHERE DAYS(PRENDATE) - DAYS(PRSTDATE) >= 0;

--6) List all department. Show name of departments. Order them in descending.
SELECT DEPTNAME
FROM DEPARTMENT
ORDER BY DEPTNAME DESC;

--7) Show name if employees and name of their department
SELECT FIRSTNME, LASTNAME, DEPTNAME
FROM EMPLOYEE, DEPARTMENT
WHERE WORKDEPT = DEPTNO;

--8) Show name of employee and their project number
SELECT FIRSTNME, LASTNAME, PROJNO, ACTNO
FROM EMPLOYEE, EMPPROJACT
WHERE EMPLOYEE.EMPNO = EMPPROJACT.EMPNO;

--9) Show name of employee and their project number (No duplication)
SELECT DISTINCT FIRSTNME, LASTNAME, PROJNO, ACTNO
FROM EMPLOYEE, EMPPROJACT
WHERE EMPLOYEE.EMPNO = EMPPROJACT.EMPNO;

--10) What department has name like 'SPIF' something?
SELECT *
FROM DEPARTMENT
WHERE DEPTNAME LIKE '%SPIF%';

--11) Who work at this 'SPIF' something?
SELECT FIRSTNME, LASTNAME
FROM EMPLOYEE, DEPARTMENT
WHERE EMPLOYEE.WORKDEPT = DEPARTMENT.DEPTNO
  and DEPTNAME LIKE '%SPIF%';

--12) Show only male of answer of question 11.
SELECT FIRSTNME, LASTNAME
FROM EMPLOYEE, DEPARTMENT
WHERE EMPLOYEE.WORKDEPT = DEPARTMENT.DEPTNO
  and DEPTNAME LIKE '%SPIF%'
  and SEX = 'M';

--13) Show name of employee and name of their project
SELECT DISTINCT FIRSTNME, LASTNAME, PROJNAME
FROM EMPLOYEE, EMPPROJACT, PROJECT
WHERE EMPLOYEE.EMPNO = EMPPROJACT.EMPNO
  and PROJECT.PROJNO = EMPPROJACT.PROJNO;

--14) Who works on project running less than 300 days?
SELECT FIRSTNME, LASTNAME, PROJNAME, DAYS(PRENDATE) - DAYS(PRSTDATE) as PROJ_DAYS
FROM EMPLOYEE, EMPPROJACT, PROJECT
WHERE EMPLOYEE.EMPNO = EMPPROJACT.EMPNO
  and PROJECT.PROJNO = EMPPROJACT.PROJNO
  and DAYS(PRENDATE) - DAYS(PRSTDATE) between 1 and 300;

--15) Is there anyone have no bonus or commission?
SELECT FIRSTNME, LASTNAME
FROM EMPLOYEE
WHERE BONUS = 0 OR COMM = 0;

--16) Is there anyone else in question 15?
SELECT FIRSTNME, LASTNAME
FROM EMPLOYEE
WHERE BONUS is NULL OR COMM is NULL;

--17) Which column in table DEPARTMENT has NULL value?
SELECT *
FROM DEPARTMENT
WHERE LOCATION is NULL;

SELECT *
FROM DEPARTMENT
WHERE LOCATION = 'NULL';

--18) Print all employee whose name starts with J?
SELECT FIRSTNME, LASTNAME
FROM EMPLOYEE
WHERE FIRSTNME LIKE 'J%';

--19) What time is it?
SELECT CURRENT_DATE AS CURRENT_DATE, CURRENT_TIME AS CURRENT_TIME
FROM sysibm.SYSDUMMY1;

--20) Which time zone is that?
SELECT CURRENT_TIMESTAMP AS CURRENT_TIMESTAMP,
       CURRENT_TIMEZONE AS CURRENT_TIMEZONE,
       CURRENT_TIMESTAMP - CURRENT_TIMEZONE as A
FROM sysibm.SYSDUMMY1;

--21) Show me last three digit of your id
SELECT 212
FROM sysibm.SYSDUMMY1;

-------------------------------------------------------------------------
SELECT * FROM EMPLOYEE;
SELECT * FROM PROJECT;
SELECT * FROM DEPARTMENT;
SELECT * FROM EMPPROJACT;