SELECT * from DB2INST1.EMPLOYEE;

--1.) Show lastname, salary, and phone number of employee
SELECT LASTNAME, SALARY, PHONENO from DB2INST1.EMPLOYEE;

--2.) Show lastname, salary and comm from employee
SELECT LASTNAME, SALARY, BONUS, COMM FROM DB2INST1.EMPLOYEE;

--3.) Show firstname, lastname and total income of each employee
SELECT FIRSTNME as FIRSTNAME, LASTNAME, SALARY+BONUS+COMM as TOTAL_INCOME from DB2INST1.EMPLOYEE;

--4.) Show name of employee and his/her date of birth
SELECT FIRSTNME, LASTNAME, BIRTHDATE from DB2INST1.EMPLOYEE;

--5.) Show name of employee, his/her date of birth, and age
SELECT FIRSTNME, LASTNAME, BIRTHDATE, YEAR(BIRTHDATE) as BIRTHYEAR FROM DB2INST1.EMPLOYEE;

SELECT FIRSTNME, LASTNAME, BIRTHDATE, 2023 - YEAR(BIRTHDATE) as AGE FROM DB2INST1.EMPLOYEE; --Incorrect

SELECT FIRSTNME, LASTNAME, BIRTHDATE, year(CURRENT_DATE - BIRTHDATE) as AGE FROM DB2INST1.EMPLOYEE;

--6.) Show FIRSTNAME, LASTNAME, MIDDLENAME, and gender of employee
SELECT FIRSTNME, LASTNAME, MIDINIT, SEX FROM DB2INST1.EMPLOYEE;

--7.) Show FIRSTNAME, LASTNAME, MIDDLENAME, and gender of employee (Lady first, Gentleman is not selfish)
SELECT FIRSTNME, MIDINIT, LASTNAME, SEX FROM DB2INST1.EMPLOYEE ORDER BY SEX;

--8.) Show FIRSTNAME, LASTNAME, MIDDLENAME, and gender of employee (Men are selfish)
SELECT FIRSTNME, MIDINIT, LASTNAME, SEX FROM DB2INST1.EMPLOYEE ORDER BY SEX DESC;

--9.) Show the employee. Order from highest to lowest income
SELECT FIRSTNME as FIRSTNAME, LASTNAME, SALARY, BONUS, COMM, SALARY+BONUS+COMM as TOTAL_INCOME --Got NULL data
from DB2INST1.EMPLOYEE ORDER BY TOTAL_INCOME DESC;

SELECT FIRSTNME as FIRSTNAME, LASTNAME, SALARY, BONUS, COMM, SALARY+ COALESCE(BONUS,0) + COALESCE(COMM,0) as TOTAL_INCOME
from DB2INST1.EMPLOYEE ORDER BY TOTAL_INCOME DESC;

SELECT FIRSTNME as FIRSTNAME, LASTNAME, SALARY, BONUS, COMM, COALESCE(SALARY+BONUS+COMM,0)  as TOTAL_INCOME
from DB2INST1.EMPLOYEE ORDER BY TOTAL_INCOME DESC;

--10.) Show name of employee and their salary after 5% increase
SELECT FIRSTNME, LASTNAME, SALARY, SALARY+SALARY*0.05 as INCREASED_SALARY FROM DB2INST1.EMPLOYEE;

SELECT FIRSTNME, LASTNAME, SALARY, SALARY*1.05 as INCREASED_SALARY FROM DB2INST1.EMPLOYEE;

--11.) I'm tired of db2inst1. Let import data into your own table [EMPLOYEE] (under your schema)
SELECT * FROM EMPLOYEE;

--12.) Do the same thing to table department
--13.) Do the same thing to table project
--14.) Do the same thing to table empprojact

--15.) Show name and start and end date of all project
SELECT PROJNAME, PRSTDATE, PRENDATE FROM PROJECT;

-----------------------------------------------------------------------
SELECT * FROM EMPLOYEE;

GRANT SELECT ON EMPLOYEE TO USER KITTIPHOD;
GRANT SELECT ON DEPARTMENT TO USER KITTIPHOD;
GRANT SELECT ON PROJECT TO USER KITTIPHOD;
GRANT SELECT ON EMPPROJACT TO USER KITTIPHOD;